<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ratelimit/ratelimit.proto

namespace Pb\Lyft\Ratelimit;

if (false) {
    /**
     * This class is deprecated. Use Pb\Lyft\Ratelimit\RateLimit\Unit instead.
     * @deprecated
     */
    class RateLimit_Unit {}
}
class_exists(RateLimit\Unit::class);
@trigger_error('Pb\Lyft\Ratelimit\RateLimit_Unit is deprecated and will be removed in the next major release. Use Pb\Lyft\Ratelimit\RateLimit\Unit instead', E_USER_DEPRECATED);

