<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ratelimit/ratelimit.proto

namespace Pb\Lyft\Ratelimit;

if (false) {
    /**
     * This class is deprecated. Use Pb\Lyft\Ratelimit\RateLimitResponse\DescriptorStatus instead.
     * @deprecated
     */
    class RateLimitResponse_DescriptorStatus {}
}
class_exists(RateLimitResponse\DescriptorStatus::class);
@trigger_error('Pb\Lyft\Ratelimit\RateLimitResponse_DescriptorStatus is deprecated and will be removed in the next major release. Use Pb\Lyft\Ratelimit\RateLimitResponse\DescriptorStatus instead', E_USER_DEPRECATED);

