<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ratelimit/ratelimit.proto

namespace Pb\Lyft\Ratelimit;

if (false) {
    /**
     * This class is deprecated. Use Pb\Lyft\Ratelimit\RateLimitDescriptor\Entry instead.
     * @deprecated
     */
    class RateLimitDescriptor_Entry {}
}
class_exists(RateLimitDescriptor\Entry::class);
@trigger_error('Pb\Lyft\Ratelimit\RateLimitDescriptor_Entry is deprecated and will be removed in the next major release. Use Pb\Lyft\Ratelimit\RateLimitDescriptor\Entry instead', E_USER_DEPRECATED);

