<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ratelimit/ratelimit.proto

namespace Pb\Lyft\Ratelimit;

if (false) {
    /**
     * This class is deprecated. Use Pb\Lyft\Ratelimit\RateLimitResponse\Code instead.
     * @deprecated
     */
    class RateLimitResponse_Code {}
}
class_exists(RateLimitResponse\Code::class);
@trigger_error('Pb\Lyft\Ratelimit\RateLimitResponse_Code is deprecated and will be removed in the next major release. Use Pb\Lyft\Ratelimit\RateLimitResponse\Code instead', E_USER_DEPRECATED);

