<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ratelimit/ratelimit.proto

namespace Pb\Lyft\Ratelimit;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Defines an actual rate limit in terms of requests per unit of time and the unit itself.
 *
 * Generated from protobuf message <code>pb.lyft.ratelimit.RateLimit</code>
 */
class RateLimit extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 requests_per_unit = 1;</code>
     */
    private $requests_per_unit = 0;
    /**
     * Generated from protobuf field <code>.pb.lyft.ratelimit.RateLimit.Unit unit = 2;</code>
     */
    private $unit = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $requests_per_unit
     *     @type int $unit
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ratelimit\Ratelimit::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 requests_per_unit = 1;</code>
     * @return int
     */
    public function getRequestsPerUnit()
    {
        return $this->requests_per_unit;
    }

    /**
     * Generated from protobuf field <code>uint32 requests_per_unit = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRequestsPerUnit($var)
    {
        GPBUtil::checkUint32($var);
        $this->requests_per_unit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pb.lyft.ratelimit.RateLimit.Unit unit = 2;</code>
     * @return int
     */
    public function getUnit()
    {
        return $this->unit;
    }

    /**
     * Generated from protobuf field <code>.pb.lyft.ratelimit.RateLimit.Unit unit = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUnit($var)
    {
        GPBUtil::checkEnum($var, \Pb\Lyft\Ratelimit\RateLimit_Unit::class);
        $this->unit = $var;

        return $this;
    }

}

