<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ratelimit/ratelimit.proto

namespace Pb\Lyft\Ratelimit\RateLimit;

/**
 * Protobuf type <code>pb.lyft.ratelimit.RateLimit.Unit</code>
 */
class Unit
{
    /**
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>SECOND = 1;</code>
     */
    const SECOND = 1;
    /**
     * Generated from protobuf enum <code>MINUTE = 2;</code>
     */
    const MINUTE = 2;
    /**
     * Generated from protobuf enum <code>HOUR = 3;</code>
     */
    const HOUR = 3;
    /**
     * Generated from protobuf enum <code>DAY = 4;</code>
     */
    const DAY = 4;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Unit::class, \Pb\Lyft\Ratelimit\RateLimit_Unit::class);

